import { PostType } from "@/types/posts";

export const mockPosts: PostType[] = [
  {
    id: "1jx93b7",
    userId: "nXMWOksOigd37ME0fmQXKYL76Wn2",
    author: "LeasingLegend42",
    title: "AI tools for verifying tenant income?",
    body: "Has anyone tried using AI-driven tools for detecting fake paystubs or bank statements? Curious how reliable they are compared to manual verification.",
    topComments: [
      {
        author: "RentGuru88",
        body: "We’ve been using Snappt for about a year now—catches most of the forged docs before they get to leasing.",
      },
      {
        author: "ComplianceNerd",
        body: "Check out Plaid integrations too. They pull transaction data directly from banks, which cuts down on fraud massively.",
      },
    ],
    score: 42,
    url: "https://www.reddit.com/r/PropertyManagement/comments/1jx93b7/ai_tools_for_verifying_tenant_income/",
    platform: "Reddit | PropertyManagement",
    postCreatedAt: "2025-03-15T12:47:20.000Z",
    createdAt: "2025-03-15T12:48:00.000Z",
    boardColumnId: "research",
    columnRank: "a0",
    action: "engage",
    explanation:
      "This post highlights interest in technology-driven fraud prevention, aligning with Tire Swing’s positioning around document intelligence for compliance workflows.",
    engagementTarget: "post",
    priority: "high",
    recommendedReply: {
      reply:
        "Great question! Tire Swing’s AI verification module detects subtle document edits automatically. Happy to share a quick demo.",
      replyTarget: "post",
      targetComment: null,
    },
  },
  {
    id: "1jx93b8",
    userId: "5EZPxYkAbc37ME0fmQXKYL76Wn2",
    author: "AffordableAly",
    title: "What’s your biggest compliance pain point this quarter?",
    body: "For me it’s tracking new HUD guidelines. The updates come out fast, and our documentation gets messy real quick.",
    topComments: [
      {
        author: "HousingHero",
        body: "Same here. Our team uses an internal spreadsheet, but it’s hard to keep it updated across regions.",
      },
    ],
    score: 23,
    url: "https://www.reddit.com/r/Compliance/comments/1jx93b8/biggest_compliance_pain_points/",
    platform: "Reddit | Compliance",
    postCreatedAt: "2025-04-01T10:10:00.000Z",
    createdAt: "2025-04-01T10:11:00.000Z",
    boardColumnId: "engagement",
    columnRank: "a1",
    action: "listen",
    explanation:
      "This discussion exposes recurring issues with documentation control—key for Tire Swing to showcase automated compliance updates.",
    engagementTarget: "comments",
    priority: "medium",
    recommendedReply: {
      reply:
        "Totally feel this! Tire Swing’s compliance tracker automatically flags HUD updates and syncs changes to your document templates.",
      replyTarget: "post",
      targetComment: null,
    },
  },
  {
    id: "1jx93b9",
    userId: "mQW8dKJ5r6t9v0YpXw",
    author: "TechLandlord",
    title: "Integrating Plaid with housing applications?",
    body: "We’re exploring Plaid to verify tenant income directly via bank data. Has anyone had issues with tenant privacy or data permissions?",
    topComments: [
      {
        author: "TenantTechie",
        body: "We had some pushback early on, but once we explained data privacy terms, applicants were fine.",
      },
      { author: "LeaseFlow", body: "The key is transparency—showing what data you access and why." },
    ],
    score: 37,
    url: "https://www.reddit.com/r/PropertyManagement/comments/1jx93b9/integrating_plaid_with_housing_apps/",
    platform: "Reddit | PropTech",
    postCreatedAt: "2025-05-10T08:20:45.000Z",
    createdAt: "2025-05-10T08:21:10.000Z",
    boardColumnId: "insights",
    columnRank: "a2",
    action: "engage",
    explanation:
      "This thread signals rising adoption of fintech APIs in housing verification—an opportunity to position Tire Swing within the digital income verification space.",
    engagementTarget: "post",
    priority: "medium",
    recommendedReply: {
      reply:
        "We’ve seen similar results—clear consent messaging builds trust. Tire Swing integrates securely with Plaid for automated income verification.",
      replyTarget: "post",
      targetComment: null,
    },
  },
  {
    id: "1jx93c0",
    userId: "eL8PQkSkYzM93AL09Dn",
    author: "HUDWatcher",
    title: "Anyone else overwhelmed by new Fair Housing training mandates?",
    body: "It feels like every state rolled out their own requirements. Any tool that centralizes training tracking?",
    topComments: [],
    score: 15,
    url: "https://www.reddit.com/r/HousingPolicy/comments/1jx93c0/fair_housing_training_mandates/",
    platform: "Reddit | HousingPolicy",
    postCreatedAt: "2025-06-02T14:33:00.000Z",
    createdAt: "2025-06-02T14:33:45.000Z",
    boardColumnId: "painpoints",
    columnRank: "a3",
    action: "listen",
    explanation:
      "This pain point showcases administrative overload—a chance for Tire Swing to position its platform as simplifying multi-jurisdictional compliance.",
    engagementTarget: "post",
    priority: "high",
    recommendedReply: {
      reply:
        "We’re working on centralizing state-specific Fair Housing tracking—might be exactly what you’re describing!",
      replyTarget: "post",
      targetComment: null,
    },
  },
  {
    id: "1jx93c1",
    userId: "bR9tJw8oA4v37XP0kmN",
    author: "DataDrivenLeaser",
    title: "Tracking renewal compliance efficiently?",
    body: "How do you handle HUD recertification dates at scale? We’ve missed deadlines before—looking for automation ideas.",
    topComments: [
      { author: "ComplianceGuru", body: "We built a Google Sheet with reminders, but it’s too manual for 200+ units." },
    ],
    score: 29,
    url: "https://www.reddit.com/r/Compliance/comments/1jx93c1/tracking_renewal_compliance/",
    platform: "Reddit | Compliance",
    postCreatedAt: "2025-06-14T16:00:00.000Z",
    createdAt: "2025-06-14T16:00:45.000Z",
    boardColumnId: "followups",
    columnRank: "a4",
    action: "engage",
    explanation:
      "This post illustrates the burden of renewal tracking. Tire Swing’s workflow automation directly addresses missed deadlines.",
    engagementTarget: "post",
    priority: "high",
    recommendedReply: {
      reply:
        "Tire Swing automates HUD recertification reminders and syncs them to your unit database. No more deadline stress!",
      replyTarget: "post",
      targetComment: null,
    },
  },
  {
    id: "1jx93c2",
    userId: "xS9uTnDqRkM48LP2",
    author: "LeasingPro101",
    title: "Document retention best practices?",
    body: "How long are you all keeping old tenant income docs before shredding or archiving? HUD guidance seems unclear.",
    topComments: [],
    score: 11,
    url: "https://www.reddit.com/r/PropertyManagement/comments/1jx93c2/document_retention_best_practices/",
    platform: "Reddit | PropertyManagement",
    postCreatedAt: "2025-07-10T09:55:00.000Z",
    createdAt: "2025-07-10T09:55:45.000Z",
    boardColumnId: "research",
    columnRank: "a5",
    action: "listen",
    explanation:
      "Document lifecycle management is a recurring concern. Tire Swing can highlight its secure archiving and retention automation features.",
    engagementTarget: "post",
    priority: "low",
    recommendedReply: null,
  },
  {
    id: "1jx93c3",
    userId: "qKLM78dEoWz93LK0ab",
    author: "TenantTechTalk",
    title: "Anyone comparing Snappt vs Plaid for doc verification?",
    body: "We’re evaluating both for tenant verification. Any insights on accuracy or ease of integration?",
    topComments: [],
    score: 33,
    url: "https://www.reddit.com/r/PropTech/comments/1jx93c3/snappt_vs_plaid_doc_verification/",
    platform: "Reddit | PropTech",
    postCreatedAt: "2025-07-22T15:44:00.000Z",
    createdAt: "2025-07-22T15:44:20.000Z",
    boardColumnId: "comparison",
    columnRank: "a6",
    action: "engage",
    explanation:
      "This post reflects active vendor comparison behavior, indicating a strong buying signal for verification solutions like Tire Swing.",
    engagementTarget: "post",
    priority: "medium",
    recommendedReply: {
      reply:
        "We’ve benchmarked both and built Tire Swing to combine Plaid’s data depth with Snappt-style document forensics. Happy to share insights!",
      replyTarget: "post",
      targetComment: null,
    },
  },
  {
    id: "1jx93c4",
    userId: "yPL6r9kR8Tg39XM0qrN",
    author: "AffordableOps",
    title: "Collecting paystubs during renewal season—streamline tips?",
    body: "We collect hundreds of paystubs each quarter. Looking for automation ideas or API tools to cut back on email chaos.",
    topComments: [],
    score: 18,
    url: "https://www.reddit.com/r/PropertyManagement/comments/1jx93c4/collecting_paystubs_streamline/",
    platform: "Reddit | AffordableHousing",
    postCreatedAt: "2025-08-05T12:12:00.000Z",
    createdAt: "2025-08-05T12:13:00.000Z",
    boardColumnId: "automation",
    columnRank: "a7",
    action: "listen",
    explanation:
      "High-volume document collection is a major friction point. Tire Swing can showcase automated paystub ingestion and categorization.",
    engagementTarget: "post",
    priority: "medium",
    recommendedReply: null,
  },
  {
    id: "1jx93c5",
    userId: "pLMN0qW8bA23tRE0",
    author: "PropTechFan",
    title: "Using AI to detect altered PDFs—does it actually work?",
    body: "We ran a few tests with free AI PDF checkers and got mixed results. Curious if paid tools really outperform.",
    topComments: [],
    score: 54,
    url: "https://www.reddit.com/r/PropTech/comments/1jx93c5/ai_to_detect_altered_pdfs/",
    platform: "Reddit | PropTech",
    postCreatedAt: "2025-09-01T10:00:00.000Z",
    createdAt: "2025-09-01T10:01:00.000Z",
    boardColumnId: "research",
    columnRank: "a8",
    action: "engage",
    explanation:
      "AI-based PDF detection is central to Tire Swing’s differentiation—engaging here positions the brand as a credible expert.",
    engagementTarget: "post",
    priority: "high",
    recommendedReply: {
      reply:
        "Yes! Paid AI tools like Tire Swing use document forensics and font-level analysis to detect subtle tampering far beyond free tools.",
      replyTarget: "post",
      targetComment: null,
    },
  },
  {
    id: "1jx93c6",
    userId: "uR8qLpTn90r3MKL4",
    author: "LeaseLogic",
    title: "Keeping up with changing state income verification rules",
    body: "California, Texas, and Florida all updated their income verification standards in the last six months—how are you all staying current?",
    topComments: [],
    score: 26,
    url: "https://www.reddit.com/r/Compliance/comments/1jx93c6/state_income_verification_rules/",
    platform: "Reddit | Compliance",
    postCreatedAt: "2025-10-01T11:15:00.000Z",
    createdAt: "2025-10-01T11:15:45.000Z",
    boardColumnId: "updates",
    columnRank: "a9",
    action: "listen",
    explanation:
      "Constant regulatory shifts are an ongoing compliance challenge—Tire Swing can demonstrate real-time rule tracking and update automation.",
    engagementTarget: "post",
    priority: "high",
    recommendedReply: {
      reply:
        "We built Tire Swing to automatically pull and track state-level compliance updates. Cuts through the chaos of constant changes.",
      replyTarget: "post",
      targetComment: null,
    },
  },
];
