export enum FIREBASE_COLLECTION_ENUMS {
  USERS_COLLECTION = "users",
  POSTS_COLLECTION = "posts",
  OBJECTIVES_COLLECTION = "objectives",
  LOGS_COLLECTION = "logs",
  INVITES_COLLECTION = "invites",
}
