import { collection } from "firebase/firestore";

import { FIREBASE_COLLECTION_ENUMS, FIREBASE_DOCUMENT_ENUMS } from "@/enums/firebase";
import { db } from "@/firebase";

export const USERS_COLLECTION_REF = collection(db, FIREBASE_COLLECTION_ENUMS.USERS_COLLECTION);

export const REDDIT_SCRAPER_SUBSCRIBER_COLLECTION_REF = collection(
  db,
  FIREBASE_COLLECTION_ENUMS.SCRAPERS_COLLECTION,
  FIREBASE_DOCUMENT_ENUMS.REDDIT_SCRAPER_DOCUMENT,
  FIREBASE_COLLECTION_ENUMS.SUBSCRIBERS_COLLECTION,
);

export const INVITES_COLLECTION_REF = collection(db, FIREBASE_COLLECTION_ENUMS.INVITES_COLLECTION);
